spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: event-wikimedia
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
server:
  port: 8081